# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mnw_pb2 as mnw__pb2


class MnwServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/mnw.MnwService/Hello',
                request_serializer=mnw__pb2.Params.SerializeToString,
                response_deserializer=mnw__pb2.Status.FromString,
                )
        self.GetState = channel.unary_stream(
                '/mnw.MnwService/GetState',
                request_serializer=mnw__pb2.Params.SerializeToString,
                response_deserializer=mnw__pb2.StateParams.FromString,
                )
        self.Swap = channel.stream_stream(
                '/mnw.MnwService/Swap',
                request_serializer=mnw__pb2.SwapParams.SerializeToString,
                response_deserializer=mnw__pb2.SwapParams.FromString,
                )


class MnwServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Swap(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MnwServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=mnw__pb2.Params.FromString,
                    response_serializer=mnw__pb2.Status.SerializeToString,
            ),
            'GetState': grpc.unary_stream_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=mnw__pb2.Params.FromString,
                    response_serializer=mnw__pb2.StateParams.SerializeToString,
            ),
            'Swap': grpc.stream_stream_rpc_method_handler(
                    servicer.Swap,
                    request_deserializer=mnw__pb2.SwapParams.FromString,
                    response_serializer=mnw__pb2.SwapParams.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mnw.MnwService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MnwService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mnw.MnwService/Hello',
            mnw__pb2.Params.SerializeToString,
            mnw__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mnw.MnwService/GetState',
            mnw__pb2.Params.SerializeToString,
            mnw__pb2.StateParams.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Swap(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mnw.MnwService/Swap',
            mnw__pb2.SwapParams.SerializeToString,
            mnw__pb2.SwapParams.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
