# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mnw.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mnw.proto',
  package='mnw',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tmnw.proto\x12\x03mnw\"\x15\n\x06Params\x12\x0b\n\x03src\x18\x01 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x1d\n\x0bStateParams\x12\x0e\n\x06params\x18\x01 \x01(\x0c\")\n\nSwapParams\x12\x0b\n\x03src\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\x0c\x32\x90\x01\n\nMnwService\x12#\n\x05Hello\x12\x0b.mnw.Params\x1a\x0b.mnw.Status\"\x00\x12-\n\x08GetState\x12\x0b.mnw.Params\x1a\x10.mnw.StateParams\"\x00\x30\x01\x12.\n\x04Swap\x12\x0f.mnw.SwapParams\x1a\x0f.mnw.SwapParams\"\x00(\x01\x30\x01\x62\x06proto3'
)




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='mnw.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='mnw.Params.src', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=39,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='mnw.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='mnw.Status.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=65,
)


_STATEPARAMS = _descriptor.Descriptor(
  name='StateParams',
  full_name='mnw.StateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='mnw.StateParams.params', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=96,
)


_SWAPPARAMS = _descriptor.Descriptor(
  name='SwapParams',
  full_name='mnw.SwapParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='mnw.SwapParams.src', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='mnw.SwapParams.params', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['StateParams'] = _STATEPARAMS
DESCRIPTOR.message_types_by_name['SwapParams'] = _SWAPPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'mnw_pb2'
  # @@protoc_insertion_point(class_scope:mnw.Params)
  })
_sym_db.RegisterMessage(Params)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'mnw_pb2'
  # @@protoc_insertion_point(class_scope:mnw.Status)
  })
_sym_db.RegisterMessage(Status)

StateParams = _reflection.GeneratedProtocolMessageType('StateParams', (_message.Message,), {
  'DESCRIPTOR' : _STATEPARAMS,
  '__module__' : 'mnw_pb2'
  # @@protoc_insertion_point(class_scope:mnw.StateParams)
  })
_sym_db.RegisterMessage(StateParams)

SwapParams = _reflection.GeneratedProtocolMessageType('SwapParams', (_message.Message,), {
  'DESCRIPTOR' : _SWAPPARAMS,
  '__module__' : 'mnw_pb2'
  # @@protoc_insertion_point(class_scope:mnw.SwapParams)
  })
_sym_db.RegisterMessage(SwapParams)



_MNWSERVICE = _descriptor.ServiceDescriptor(
  name='MnwService',
  full_name='mnw.MnwService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=142,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='mnw.MnwService.Hello',
    index=0,
    containing_service=None,
    input_type=_PARAMS,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetState',
    full_name='mnw.MnwService.GetState',
    index=1,
    containing_service=None,
    input_type=_PARAMS,
    output_type=_STATEPARAMS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Swap',
    full_name='mnw.MnwService.Swap',
    index=2,
    containing_service=None,
    input_type=_SWAPPARAMS,
    output_type=_SWAPPARAMS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MNWSERVICE)

DESCRIPTOR.services_by_name['MnwService'] = _MNWSERVICE

# @@protoc_insertion_point(module_scope)
